### ISSUE TITLE
[eslint-plugin-import:resolver:vite] Cannot use import statement outside a module

### ISSUE THREAD

**Issue by thNel** [pzmosquito/eslint-import-resolver-vite#13]
Typescript, Vite, React project.

.eslintrc.json
`{
  "root": true,
  "env": {
    "browser": true,
    "es2020": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react-hooks/recommended"
  ],
  "ignorePatterns": [
    "dist",
    "node_modules",
    ".eslintrc.cjs"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "parser": "@typescript-eslint/parser",
    "ecmaFeatures": {
      "jsx": false
    }
  },
  "plugins": [
    "react-refresh",
    "@typescript-eslint",
    "prettier",
    "import"
  ],
  "settings": {
    "import/resolver": {
      "alias": {
        "map": [
          [
            "@",
            "./src"
          ]
        ],
        "extensions": [
          ".ts",
          ".tsx"
        ]
      },
      "node": {
        "moduleDirectory": [
          "node_modules",
          "src/"
        ]
      },
      "vite": {
        "namedExport": "viteConfig",
        "configPath": "vite.config.ts"
      }
    },
    "import/ignore": [
      "node_modules"
    ]
  },
  "rules": {
    "react-refresh/only-export-components": [
      "warn",
      {
        "allowConstantExport": true
      }
    ],
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-unused-vars": "error",
    "no-debugger": "error",
    "import/extensions": [
      "error",
      "ignorePackages",
      {
        "": "never",
        "js": "never",
        "ts": "never",
        "jsx": "never",
        "tsx": "never"
      }
    ],
    "import/no-unresolved": [
      0
    ]
  }
}`

tsconfig.json
`{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": [
      "ESNext",
      "DOM",
      "DOM.Iterable"
    ],
    "module": "ESNext",
    "skipLibCheck": true,
    "paths": {
      "@mui/styled-engine": [
        "./node_modules/@mui/styled-engine-sc"
      ],
      "@/*": ["src/*"]
    },
    /* Bundler mode */
    "moduleResolution": "Node",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "./",
    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "src"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}`

while building it logs two similar strings:
![image](https://github.com/pzmosquito/eslint-import-resolver-vite/assets/92314896/9c36f800-e2de-4c3a-9c3b-feb5e6cbdc32)

**Comment by thNel** [comment]
Also, package.json includes "type": "module"

And index.html script tag has attribute type="module"

**Comment by pzmosquito** [comment]
The issue has been discussed [here](https://github.com/pzmosquito/eslint-import-resolver-vite/issues/1#issuecomment-1200626994) and [here](https://github.com/pzmosquito/eslint-import-resolver-vite/issues/12). It's a limitation of `eslint` and `eslint-plugin-import`

**Comment by thNel** [comment]
Well, I do not have any "require()" syntax. Only " import { Something } from './file.ts' ". But still have theese logs.

Also I can share the repository with blank project and this logs. Maybe you will see something wrong

https://github.com/thNel/parsed

**Comment by pzmosquito** [comment]
> Well, I do not have any "require()" syntax. Only " import { Something } from './file.ts' ". But still have theese logs

This plugin uses `require()` to retrieve Vite config.

**Comment by thNel** [comment]
> > Well, I do not have any "require()" syntax. Only " import { Something } from './file.ts' ". But still have theese logs
> 
> This plugin uses `require()` to retrieve Vite config.

Ah, ok.. That why we needed named export when uses functional definition in vite.config)

**Comment by pzmosquito** [comment]
> > > Well, I do not have any "require()" syntax. Only " import { Something } from './file.ts' ". But still have theese logs
> > 
> > 
> > This plugin uses `require()` to retrieve Vite config.
> 
> Ah, ok.. That why we needed named export when uses functional definition in vite.config)

Yes unfortunately. Vite only provides resolved config asynchronously.

**Comment by n0099** [comment]
> Yes unfortunately. Vite only provides resolved config asynchronously.

No, async exporting is [the nature of esm](https://stackoverflow.com/questions/77115924/is-the-loading-of-esmodule-asynchronous), not the vite config specified.
And we can only using [dynamic `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) that returns a `Promise` to import esm into cjs.

> Ah, ok.. That why we needed named export when uses functional definition in vite.config)

It's also not necessary with the latest `2.0.0-beta1` since the [`vite.defineConfig()`](https://github.com/vitejs/vite/blob/5684fcd8d27110d098b3e1c19d851f44251588f1/packages/vite/index.cjs#L6) is just a [identify function](https://en.wikipedia.org/wiki/Identity_function) to provide [typing information](https://github.com/vitejs/vite/blob/5684fcd8d27110d098b3e1c19d851f44251588f1/packages/vite/src/node/config.ts#L111).
Please checkout https://github.com/pzmosquito/eslint-import-resolver-vite/issues/12#issuecomment-1858743165 for a resolution of this issue.
