### ISSUE TITLE
Version 1.3.0 does not exist on npm

### ISSUE THREAD

**Issue by davidavz** [pzmosquito/eslint-import-resolver-vite#14]
I think there is something wrong with version `1.3.0` which can not be found anymore on npm : `No matching version found for eslint-import-resolver-vite@1.3.0` https://www.npmjs.com/package/eslint-import-resolver-vite?activeTab=versions

**Comment by pzmosquito** [comment]
The version `1.3.0` has a serious issue so that I had to take it off in order to avoid causing more problems. Please use `1.3.1` instead, sorry about the inconvenience. I also marked the `1.3.0` as deprecated even though it's not showing up on NPM registry.
