### ISSUE TITLE
Version 1.3.0 is gone from NPM registry

### ISSUE THREAD

**Issue by Knogobert** [pzmosquito/eslint-import-resolver-vite#15]
Got this error `npm ERR! 404  "eslint-import-resolver-vite@https://registry.npmjs.org/eslint-import-resolver-vite/-/eslint-import-resolver-vite-1.3.0.tgz" is not in this registry.` in my CI/CD log. Hindering me from launching.

It was easily solved by running `npm i eslint-import-resolver-vite@1.3.1`. But the package is missing from https://www.npmjs.com/package/eslint-import-resolver-vite?activeTab=versions

Perhaps you could put the package back if it's still good?
Hope this helps anybody

**Comment by pzmosquito** [comment]
The version `1.3.0` had a serious issue so I had to pull it off to avoid causing more problem. I apologize for the inconvenience.

dup of #14
