### ISSUE TITLE
vite.config.ts support?

### ISSUE THREAD

**Issue by whaaaley** [pzmosquito/eslint-import-resolver-vite#24]
I use a vite.config.ts file, but currently getting this error in vscode
![image](https://github.com/user-attachments/assets/7e645592-8d41-494f-b366-7b699fc42369)

**Comment by pzmosquito** [comment]
The error seems to be related to the .ts extension. This plugin doesn’t handle extensions, it only resolves the alias. Please check your ESLint configuration.
