### ISSUE TITLE
Allow CJS configuration with no default property.

### ISSUE THREAD

**Issue by FezVrasta** [pzmosquito/eslint-import-resolver-vite#4]
The plugin right now doesn't allow a config that simply exports itself with `module.exports = { ...config_here }`, it requires it to have either `module.exports = { default: { ...config_here } }` or a different property that then has to be specified in the plugin config.

Ideally the default option should be to accept the whole `module.exports` as config as that's going to be the most common use case if the consumer is using CJS.

**Comment by pzmosquito** [comment]
I'll add support for CJS config without needing the `default`. This plugin currently assumes the config file is written in ESM as all the examples on Vite website are using ESM.

**Comment by algreasley** [comment]
and typescript?

**Comment by pzmosquito** [comment]
> and typescript?

please create a separate issue for it (and PR is always welcome).

**Comment by hackel** [comment]
Any progress in fixing this?

I tried the workaround, but I get `Unexpected top-level property "default"`.  I looked into migrating to the new flat ESM config format, but the plugins I use don't have their recommended configs in ESM format yet.

**Comment by pzmosquito** [comment]
> Any progress in fixing this?
> 
> I tried the workaround, but I get `Unexpected top-level property "default"`. I looked into migrating to the new flat ESM config format, but the plugins I use don't have their recommended configs in ESM format yet.

I'm planning for the next release, which will include this issue. I don't have a timeline but it shouldn't be too long

**Comment by pzmosquito** [comment]
This is supported in [1.1.0](https://github.com/pzmosquito/eslint-import-resolver-vite/releases/tag/1.1.0) now.
