### ISSUE TITLE
Resolve static asset imports from `public` directory

### ISSUE THREAD

**Issue by musjj** [pzmosquito/eslint-import-resolver-vite#7]
https://vitejs.dev/guide/assets.html#the-public-directory

Imports from the `public` directory is not resolved correctly:

```js
 import foo from "/images/foo.jpg";       eslint: Unable to resolve path to module '/images/foo.jpg'.
```

It would be nice if this could be supported.

**Comment by pzmosquito** [comment]
Thanks for the suggestion. I'll add the support in the next release.

**Comment by pzmosquito** [comment]
Reading the doc again, it states: `If you have assets that are: Never referenced in source code`, and also in the note:`Assets in public cannot be imported from JavaScript`.

It looks like it's not recommended to import assets in the `public` directory. So I'm hesitant to make the change. I think it'll be better that you move the assets out of the `public` directory if you need to reference them in the source code.

**Comment by musjj** [comment]
It's true that you don't *have* to import it, but Vite explicitly supports public imports. IMO it's usually safer to do it, because now the bundler can ensure that all the assets statically referenced in the code are valid at bundle time.

Even the official Vite template is doing it:

```typescript
import viteLogo from '/vite.svg'
```

As for:

> Assets in public cannot be imported from JavaScript.

The wording is a bit vague, but I think this is referring to importing files explictly from the `public` directory like this:

```typescript
import image from "/public/image.png"
```

You will get this warning message:

```
Assets in public cannot be imported from JavaScript.
Instead of /public/image.png, put the file in the src directory, and use /src/image.png instead.
files in the public directory are served at the root path.
Instead of /public/image.png, use /image.png.
```

But it still works anyways, both with the dev server and the build. I do think it's non-idiomatic though, because the public directory is customizable on the project-level, so hardcoding it is a bit inelegant.

**Comment by pzmosquito** [comment]
I get where you're coming from, and I totally understand your point. My only hesitation is that the behavior can be changed anytime without warning, especially because it's already mentioned as not recommended in the docs. I'll implement it in a way that the plugin won't go haywire if the Vite behavior is changed. I'll include this change in the next release.

**Comment by nerdchanii** [comment]
Hello, Is there a temporary solution to this problem?

**Comment by pzmosquito** [comment]
> Hello, Is there a temporary solution to this problem?

The temporary solution would be including the absolute public folder path in the import path, e.g. `import "/public/a.jpg"`. Based on the comment above from @musjj , you will get warning message but it will still work.

**Comment by musjj** [comment]
I'm not sure what you mean, but appending the path with `public` doesn't really change this linter's behavior (it will still fail to resolve the path). I'd suggest not changing your public imports and sticking with standard `import image from /image.png` form.

Some possible temporary solutions:
- Ignore the warning (you also may need to change your build process if you hook eslint into it)
- Use non-public assets (might be a non-starter for certain type of assets e.g. non-embedded GLTF models)
- Just disable the linter for now

**Comment by pzmosquito** [comment]
this feature is added in [1.2.0](https://github.com/pzmosquito/eslint-import-resolver-vite/releases/tag/1.2.0), thanks for the suggestion and discussion.

**Comment by musjj** [comment]
Thanks this is working perfectly, except for an error when loading the Vite config: https://github.com/pzmosquito/eslint-import-resolver-vite/pull/8

**Comment by nerdchanii** [comment]
@pzmosquito oh, cool! thanks to your works.
